server:
  port: 8081
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidperezaviles99/Bootcamp-ConfigServer
          default-label: main
          search-paths:
          - '*service'
